#include <memory>
#include <vector>
#include <deque>
#include <stack>
#include <cassert>
#include <algorithm>
#include <atomic>
#include <thread>
#include <limits>
#include <glm/glm.hpp>
#include <glm/gtx/norm.hpp>
#include "bvh_tree.h"